import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "./home.module.scss";
import Layout from "@/components/Layout";
import CtaLink from "@/components/CtaLink";
import Link from "next/link";
import Projects from "./components/Projects";
import { useTheme } from "next-themes";
import Image from "next/image";
import BlurryBackground from "@/assets/blurry-bg.png";

type Props = {};

export default function HomePage({}: Props) {
  const [mounted, setMounted] = useState(false);
  const { theme, systemTheme } = useTheme();

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  const currentTheme = theme === "system" ? systemTheme : theme;

  return (
    <div style={{ position: "relative", overflow: "hidden" }}>
      <Head>
        <title>Rocky Harris</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <div className={styles.titleContainer}>
            <Image
              className={styles.background}
              src={BlurryBackground}
              alt="Blurry Background"
              priority
            />
            <h1>Hello, I am Rocky Harris</h1>
            <h2
              className={`${styles.title} ${
                currentTheme === "dark" ? styles.dark : ""
              } text-center`}
            >
              {"I'm a Senior Full Stack Developer"}
            </h2>
            <p className={styles.subTitle}>
              
            </p>
          </div>
          <h3>Selected Projects</h3>
          <Projects />
          <CtaLink text="See others" href="/projects" full />

          <h3>About</h3>
          <p className={styles.about}>
            With a strong background in front end development frameworks such as <b>
            React, Next, Svelte, Vue.js, Laravel, WordPress and Symforny</b> as well as experience working with the
            backend techniques, I am able to create scalable, high-performance Web
            applications that provide a seamless user experience.
            Have a great learning attributes and always try to learn more and more.
            Coding and design, which I started with curiosity and
            passion, are now a big part of my life. I am interested in{" "}
            <b>Django</b> and <b>Golang</b> mostly.
          </p>
          <CtaLink text="About Me" href="/about" />
          <div
            className={`${styles.connect} ${
              currentTheme === "dark" ? styles.dark : ""
            }`}
          >
            <p>Feel free to reach out to me</p>
            <Link href="/about#connect">Let's Connect</Link>
          </div>
        </main>
      </Layout>
    </div>
  );
}
